export class InfoEncuestaPBModel{
    public user_id: number;
    public nombre: string;
    public apellidos: string;
    public empresa: string;
    public cif: string;
    public sector: string;
    public convenio: string;
    public ambito: string;
    public domicilio: string;
    public telefonos: string;
    public horarios: string;
    public web: string;
    public num_centros: number;
    public num_comunidades: number;
    public tipo: string;
    public created_at: string;
    public updated_at: string;
    public username: string;
    public email: string;
}